name: API Tests

on:
  schedule:
    - cron: '15 1 * * *'  # 1:15 UTC = 4:15 по МСК
  workflow_dispatch:     # для ручного запуска
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run API tests only
      run: |
        pytest api_project --alluredir=allure-results

    - name: Install Allure CLI
      run: |
        sudo apt update
        sudo apt install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.24.0.tgz
        tar -zxvf allure-2.34.1.tgz
        sudo mv allure-2.34.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          
    - name: Generate Allure report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Deploy Allure report to GitHub Pages
      if: always()
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        rm -rf gh-pages/allure-report
        cp -r allure-report gh-pages/
        cd gh-pages
        git add allure-report
        git commit -m "Update Allure report 🚀" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send Telegram message
      if: always()  # всегда выполняется
      run: |
        STATUS=${{ job.status }}
        if [[ "$STATUS" == "success" ]]; then
          ICON="✅"
        else
          ICON="❌"
        fi

        REPORT_URL="https://juliaschevchenko.github.io/pytest/allure-report/index.html"
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="${ICON} Job *${{ github.job }}* completed with status: *${STATUS}* in repo [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}). [Open Allure report](${REPORT_URL})" \
          -d parse_mode=Markdown