name: API Tests

on:
  schedule:
    - cron: '0 1 * * *'  # 1:00 UTC = 4:00 по МСК
  workflow_dispatch:     # для ручного запуска
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API tests only
      run: |
        pytest api_project
